# Generated by Django 6.0.6 on 2026-06-18 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant_Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('State', models.CharField(max_length=40)),
                ('District', models.CharField(max_length=30)),
                ('PinCode', models.IntegerField()),
                ('GID', models.CharField(choices=[('ADHAR', 'AADHAR'), ('PAN', 'PAN'), ('VOTER_ID', 'VOTER_ID'), ('PASSPORT', 'PASSPORT')], max_length=20)),
                ('Owner', models.CharField(choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('JOINT', 'JOINT')], max_length=40)),
                ('TypeOfConnection', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Statu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('Connection Released', 'Connection Given'), ('DISCONNECTED', 'Disconnected'), ('CONNECTING', 'Connecting'), ('FAILED', 'Failed'), ('UNKNOWN', 'Unknown')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_no', models.CharField(max_length=20, unique=True)),
                ('connection_date', models.DateField()),
                ('Applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EB.applications')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EB.statu')),
            ],
        ),
    ]
